PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
AuthenticationMethods publickey
PermitEmptyPasswords no
StrictModes yes
UsePAM yes

AllowUsers debian
LoginGraceTime 20
MaxAuthTries 3
MaxSessions 3
MaxStartups 10:30:30
PerSourceMaxStartups 3

AllowAgentForwarding no
AllowTcpForwarding no
GatewayPorts no
PermitTunnel no
X11Forwarding no
PermitUserEnvironment no

ClientAliveInterval 300
ClientAliveCountMax 2
LogLevel VERBOSE
DebianBanner no
